#����������
server:
  port: 8089
  servlet:
    #ͳһǰ׺·��
    context-path: /

  undertow:
    # ����IO�߳���, ����Ҫִ�з�����������,���ǻḺ��������, Ĭ������ÿ��CPU����һ���߳�
    io-threads: 16
    # ���������̳߳�, ��ִ������servlet������������, undertow�������̳߳���ȡ���߳�,����ֵ����ȡ����ϵͳ�ĸ���
    worker-threads: 400
    # ���µ����û�Ӱ��buffer,��Щbuffer�����ڷ��������ӵ�IO����,�е�����netty�ĳػ��ڴ����
    buffer-size: 1024
    # �Ƿ�����ֱ���ڴ�
    direct-buffers: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: true
    show-sql: true
    generate-ddl: true
  datasource: #database
    primary:  # 3.0 Datasource
      jdbc-url: jdbc:sqlserver://10.10.113.188:1433;DatabaseName=mywork
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      type: com.zaxxer.hikari.HikariDataSource
      username: ceshi
      password: ceshi
    secondary:  # 2.0 Datasource
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/dataconverterplateform
      driverClassName: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      username: postgres
      password: 123456
    hikari:
      maximum-pool-size: 100
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      max-lifetime: 1800000
      minimum-idle: 5

logging:
  level:
    root: info
